default: &default
  adapter: postgresql
  encoding: unicode
  pool: 100
  username: postgres
  password: your_password
  host: localhost

development:
  <<: *default
  database: cine_marx_development

test:
  <<: *default
  database: cine_marx_test

production:
  primary: &primary_production
    <<: *default
    database: cine_marx_production
    username: cine_marx
    password: <%= ENV["CINE_MARX_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: cine_marx_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: cine_marx_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: cine_marx_production_cable
    migrations_paths: db/cable_migrate
